services:
  edge:
    image: synthient.edge
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: on-failure:3 # TODO: Config errors should not cause restarts.
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s
    ports:
      - "8080:8080" # Match port with your config (don't forget healthcheck URL above).
    volumes:
      - ${EDGE_CONFIG:-./edge-config.yml}:/app/config.yml:ro # Specify config file path (either set EDGE_CONFIG env var or edit here).
      - ./<LOCAL-DB-PATH>.mmdb:/app/<CONFIG-DB-PATH>.mmdb:ro # Specify MMDB file path (must match path in config).
    command: [ "/app/config.yml" ]

  redis:
    image: redis:8.6.1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"